### ISSUE TITLE
New version deploy checklist

### ISSUE THREAD

**Issue by andreroggeri** [agendaodonto/server#243]
- [x] Add FIREBASE_TOKEN to the production environment
 - [x] Setup mobile to use production endpoints
 - [x] Setup mobile to change the device token after signin
 - [x] Setup the backup again
